# Generated by Django 5.2.6 on 2025-09-23 20:32

import django.db.models.deletion
import incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key identifier', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value (JSON for complex data)')),
                ('description', models.CharField(help_text='Human-readable description of this setting', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='backboneinternetnetworkincident',
            options={'ordering': ['-date_time_incident'], 'verbose_name': 'Backbone Internet Network Incident', 'verbose_name_plural': 'Backbone Internet Network Incidents'},
        ),
        migrations.AlterModelOptions(
            name='corenetworkincident',
            options={'ordering': ['-date_time_incident'], 'verbose_name': 'Core Network Incident', 'verbose_name_plural': 'Core Network Incidents'},
        ),
        migrations.AlterModelOptions(
            name='dropdownconfiguration',
            options={'ordering': ['category', 'sort_order', 'value'], 'verbose_name': 'Dropdown Configuration', 'verbose_name_plural': 'Dropdown Configurations'},
        ),
        migrations.AlterModelOptions(
            name='fileaccessnetworkincident',
            options={'ordering': ['-date_time_incident'], 'verbose_name': 'File Access Network Incident', 'verbose_name_plural': 'File Access Network Incidents'},
        ),
        migrations.AlterModelOptions(
            name='radioaccessnetworkincident',
            options={'ordering': ['-date_time_incident'], 'verbose_name': 'Radio Access Network Incident', 'verbose_name_plural': 'Radio Access Network Incidents'},
        ),
        migrations.AlterModelOptions(
            name='transportnetworkincident',
            options={'ordering': ['-date_time_incident'], 'verbose_name': 'Transport Network Incident', 'verbose_name_plural': 'Transport Network Incidents'},
        ),
        migrations.RemoveField(
            model_name='dropdownconfiguration',
            name='display_name',
        ),
        migrations.AddField(
            model_name='backboneinternetnetworkincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backboneinternetnetworkincident',
            name='correction_note',
            field=models.TextField(blank=True, help_text='Note explaining why correction is needed (for admin review)', null=True),
        ),
        migrations.AddField(
            model_name='backboneinternetnetworkincident',
            name='correction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corenetworkincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corenetworkincident',
            name='correction_note',
            field=models.TextField(blank=True, help_text='Note explaining why correction is needed (for admin review)', null=True),
        ),
        migrations.AddField(
            model_name='corenetworkincident',
            name='correction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileaccessnetworkincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileaccessnetworkincident',
            name='correction_note',
            field=models.TextField(blank=True, help_text='Note explaining why correction is needed (for admin review)', null=True),
        ),
        migrations.AddField(
            model_name='fileaccessnetworkincident',
            name='correction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radioaccessnetworkincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radioaccessnetworkincident',
            name='correction_note',
            field=models.TextField(blank=True, help_text='Note explaining why correction is needed (for admin review)', null=True),
        ),
        migrations.AddField(
            model_name='radioaccessnetworkincident',
            name='correction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportnetworkincident',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportnetworkincident',
            name='correction_note',
            field=models.TextField(blank=True, help_text='Note explaining why correction is needed (for admin review)', null=True),
        ),
        migrations.AddField(
            model_name='transportnetworkincident',
            name='correction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='cause',
            field=models.CharField(blank=True, help_text='Root cause of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='cause_other',
            field=models.CharField(blank=True, help_text="Other cause description (if cause is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backbone_incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='date_time_recovery',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved (leave empty for active incidents)', null=True, verbose_name='Date and time of RECOVERY'),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='impact_comment',
            field=models.TextField(blank=True, help_text='Detailed description of impact and comments', null=True, verbose_name='IMPACT / COMMENT'),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='interconnect_type',
            field=models.CharField(help_text='Select interconnect type from admin-configured list', max_length=100, verbose_name='INTERCONNECT TYPE'),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='link_label',
            field=models.CharField(help_text='Link name or label identification', max_length=200, verbose_name='LINK LABEL'),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='origin_other',
            field=models.CharField(blank=True, help_text="Other origin description (if origin is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='platform_igw',
            field=models.CharField(help_text='Select platform or IGW from admin-configured list', max_length=100, verbose_name='PLATFORM/IGW'),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backbone_incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='cause',
            field=models.CharField(blank=True, help_text='Root cause of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='cause_other',
            field=models.CharField(blank=True, help_text="Other cause description (if cause is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='date_time_recovery',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved (leave empty for active incidents)', null=True, verbose_name='Date and time of RECOVERY'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='dot_extremity_a',
            field=models.CharField(blank=True, help_text='DOT state for extremity A', max_length=50, null=True, verbose_name='DOT EXTREMITY(A)'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='dot_extremity_b',
            field=models.CharField(blank=True, help_text='DOT state for extremity B', max_length=50, null=True, verbose_name='DOT EXTREMITY(B)'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='extremity_a',
            field=models.CharField(blank=True, help_text='Location description for extremity A', max_length=200, null=True, verbose_name='EXTREMITY(A)'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='extremity_b',
            field=models.CharField(blank=True, help_text='Location description for extremity B', max_length=200, null=True, verbose_name='EXTREMITY(B)'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='impact_comment',
            field=models.TextField(blank=True, help_text='Detailed description of impact and comments', null=True, verbose_name='IMPACT / COMMENT'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='origin_other',
            field=models.CharField(blank=True, help_text="Other origin description (if origin is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='platform',
            field=models.CharField(help_text='Select platform from admin-configured list', max_length=100, verbose_name='PLATFORM'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='region_node',
            field=models.CharField(help_text='Select region or node from admin-configured list', max_length=100, verbose_name='REGION / NODE'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='site',
            field=models.CharField(blank=True, help_text='Site identification (optional)', max_length=100, null=True, verbose_name='SITE'),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dropdownconfiguration',
            name='category',
            field=models.CharField(help_text="Configuration category (e.g., 'transport_regions', 'wilayas')", max_length=50),
        ),
        migrations.AlterField(
            model_name='dropdownconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this option is available for selection'),
        ),
        migrations.AlterField(
            model_name='dropdownconfiguration',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='dropdownconfiguration',
            name='value',
            field=models.CharField(help_text='Display value for dropdown option', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='cause',
            field=models.CharField(blank=True, help_text='Root cause of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='cause_other',
            field=models.CharField(blank=True, help_text="Other cause description (if cause is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='date_time_recovery',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved (leave empty for active incidents)', null=True, verbose_name='Date and time of RECOVERY'),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='do_wilaya',
            field=models.CharField(help_text='Select wilaya from admin-configured list', max_length=50, verbose_name='DO / WILAYA'),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='impact_comment',
            field=models.TextField(blank=True, help_text='Detailed description of impact and comments', null=True, verbose_name='IMPACT / COMMENT'),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IPv4 or IPv6 address', validators=[incidents.models.validate_ip_address], verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='origin_other',
            field=models.CharField(blank=True, help_text="Other origin description (if origin is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='zone_metro',
            field=models.CharField(help_text='Zone or metro area identification', max_length=100, verbose_name='ZONE / METRO'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='cause',
            field=models.CharField(blank=True, help_text='Root cause of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='cause_other',
            field=models.CharField(blank=True, help_text="Other cause description (if cause is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_access_incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='date_time_recovery',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved (leave empty for active incidents)', null=True, verbose_name='Date and time of RECOVERY'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='do_wilaya',
            field=models.CharField(help_text='Select wilaya from admin-configured list', max_length=50, verbose_name='DO / WILAYA'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='impact_comment',
            field=models.TextField(blank=True, help_text='Detailed description of impact and comments', null=True, verbose_name='IMPACT / COMMENT'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IPv4 or IPv6 address', validators=[incidents.models.validate_ip_address], verbose_name='IP ADDRESS'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='origin_other',
            field=models.CharField(blank=True, help_text="Other origin description (if origin is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='site',
            field=models.CharField(help_text='Radio site identification', max_length=100, verbose_name='SITE'),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_access_incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='cause',
            field=models.CharField(blank=True, help_text='Root cause of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='cause_other',
            field=models.CharField(blank=True, help_text="Other cause description (if cause is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='date_time_recovery',
            field=models.DateTimeField(blank=True, help_text='When the incident was resolved (leave empty for active incidents)', null=True, verbose_name='Date and time of RECOVERY'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='extremity_a',
            field=models.CharField(help_text='Location description for extremity A', max_length=200, verbose_name='EXTREMITY(A)'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='extremity_b',
            field=models.CharField(help_text='Location description for extremity B', max_length=200, verbose_name='EXTREMITY(B)'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='impact_comment',
            field=models.TextField(blank=True, help_text='Detailed description of impact and comments', null=True, verbose_name='IMPACT / COMMENT'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='origin_other',
            field=models.CharField(blank=True, help_text="Other origin description (if origin is 'Other')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='region_loop',
            field=models.CharField(help_text='Select region or loop from admin-configured list', max_length=100, verbose_name='REGION / LOOP'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='responsibility',
            field=models.CharField(blank=True, choices=[('', '--- None ---'), ('A', 'A'), ('B', 'B'), ('Both', 'Both')], help_text='Responsibility assignment (optional)', max_length=4, null=True, verbose_name='RESPONSIBILITY'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='system_capacity',
            field=models.CharField(help_text='Select system or capacity from admin-configured list', max_length=100, verbose_name='SYSTEM / CAPACITY'),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='backboneinternetnetworkincident',
            table=None,
        ),
        migrations.AlterModelTable(
            name='corenetworkincident',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fileaccessnetworkincident',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radioaccessnetworkincident',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transportnetworkincident',
            table=None,
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export')], help_text='Type of action performed', max_length=10)),
                ('model_name', models.CharField(help_text='Name of the model affected', max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON representation of changes made', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='incidents_a_timesta_e078b1_idx'), models.Index(fields=['user', 'timestamp'], name='incidents_a_user_id_f9aabe_idx'), models.Index(fields=['model_name', 'timestamp'], name='incidents_a_model_n_616ffc_idx')],
            },
        ),
    ]
