# Generated by Django 5.2.6 on 2025-10-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_add_performance_indexes_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backboneinternetnetworkincident',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corenetworkincident',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileaccessnetworkincident',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radioaccessnetworkincident',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportnetworkincident',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backboneinternetnetworkincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corenetworkincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccessnetworkincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radioaccessnetworkincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportnetworkincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
