# Generated by Django 4.2.25 on 2025-10-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0003_backboneinternetnetworkincident_archived_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-friendly name for this saved search', max_length=100)),
                ('network_type', models.CharField(choices=[('transport', 'Transport Networks'), ('file_access', 'File Access Networks'), ('radio_access', 'Radio Access Networks'), ('core', 'Core Networks'), ('backbone_internet', 'Backbone Internet Networks')], help_text='Which network type this search applies to', max_length=20)),
                ('search_params', models.JSONField(default=dict, help_text='JSON object containing all search filter parameters')),
                ('description', models.CharField(blank=True, help_text='Optional description of what this search finds', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this search should load by default for this network type')),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this search has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this search was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this saved search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'network_type'], name='incidents_s_user_id_215f98_idx'), models.Index(fields=['user', 'is_default'], name='incidents_s_user_id_522473_idx'), models.Index(fields=['last_used_at'], name='incidents_s_last_us_25a6fc_idx')],
                'unique_together': {('user', 'name', 'network_type')},
            },
        ),
    ]
